import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'school Management Dashboard',
  description:
    'Generated by create next app and its Next.js School Management System',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  )
}
